services:
  backend:
    image: ghcr.io/zigmasoftware/iwms-government-backend:latest
    build: .
    env_file: .env
    ports:
      - "9001:9001"
    volumes:
      - ./media:/app/media
      - ./static:/app/static
    restart: always
