# Generated by Django 5.2.8 on 2026-08-10 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytripcollectionpoint',
            name='carried_to_assignment',
            field=models.ForeignKey(blank=True, db_column='carried_to_assignment_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carried_over_collection_points', to='app.dailytripassignment', to_field='unique_id'),
        ),
        migrations.AddField(
            model_name='dailytriphouseholdcollection',
            name='carried_to_assignment',
            field=models.ForeignKey(blank=True, db_column='carried_to_assignment_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carried_over_household_collections', to='app.dailytripassignment', to_field='unique_id'),
        ),
    ]
