# Generated by Django 5.2.8 on 2026-09-05 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    # Scoped by hand to the one field that was missing from the database.
    # `VehicleBreakdown.new_assignment` was added to the model without a
    # migration, so every read of the table SELECTed a column MySQL did not
    # have -> OperationalError 1054 and a 500 on
    # /api/v1/schedule-operations/vehicle-breakdowns/.
    #
    # makemigrations also wanted to drop
    # `unique_staff_template_per_effective_date` from alternativestafftemplate
    # in the same migration. That is a separate, pre-existing model/DB drift
    # with nothing to do with this bug, so it is deliberately left out rather
    # than dropping a live uniqueness guarantee as a side effect of a fix.
    operations = [
        migrations.AddField(
            model_name='vehiclebreakdown',
            name='new_assignment',
            field=models.ForeignKey(blank=True, db_column='new_assignment_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breakdown_source', to='app.dailytripassignment', to_field='unique_id'),
        ),
    ]
