"""
Per-API-scope, per-HTTP-method rate limits used by
app.utils.throttling.MethodScopedRateThrottle (see config/settings.py,
REST_FRAMEWORK['DEFAULT_THROTTLE_CLASSES']).

Moved out of settings.py because this table is long (one entry per API
view) and purely data — keeping it in its own file keeps settings.py
readable. Each scope name matches a view's `throttle_scope` class
attribute in app/viewsets/**. Edit a rate here to change that one API's
limit; nothing else needs to change.
"""

API_THROTTLE_RATES = {
    # Auth / sensitive endpoints — tighter limits
    # 'login': {
    #     "default": '10/minute',
    #     "GET": '10/minute',
    #     "POST": '2/minute',
    #     "PUT": '10/minute',
    #     "PATCH": '10/minute',
    #     "DELETE": '10/minute',
    # },
    'otp': {
        "default": '5/minute',
        "GET": '5/minute',
        "POST": '5/minute',
        "PUT": '5/minute',
        "PATCH": '5/minute',
        "DELETE": '5/minute',
    },
    'reset_password': {
        "default": '5/minute',
        "GET": '5/minute',
        "POST": '5/minute',
        "PUT": '5/minute',
        "PATCH": '5/minute',
        "DELETE": '5/minute',
    },
    'change_password': {
        "default": '5/minute',
        "GET": '5/minute',
        "POST": '5/minute',
        "PUT": '5/minute',
        "PATCH": '5/minute',
        "DELETE": '5/minute',
    },
    'admin_change_password': {
        "default": '5/minute',
        "GET": '5/minute',
        "POST": '5/minute',
        "PUT": '5/minute',
        "PATCH": '5/minute',
        "DELETE": '5/minute',
    },
    # Everything else — default rate, tune individually as needed
    "administrative_hierarchy": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "alternative_staff_template": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "app_module": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "area_type": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "attendance_records": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "audit_log": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "bin_collection_event": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "bins": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "block_panchayat_union": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "captcha": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "citizen_complaint_ticket": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "collection_point": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "common_audit": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "company_user_screen_column_permission": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "complaint_address_change": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "complaint_category": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "complaint_feedback": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "complaint_language": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "complaint_module": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "complaint_notification": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "complaint_priority": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "complaint_reopen_history": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "complaint_routing_rule": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "complaint_sla_rule": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "complaint_source": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "complaint_status": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "complaint_subcategory": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "complaint_team": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "complaint_ticket": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "continent": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "contractor_user_type": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "corporation": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "country": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "customer_access_configuration": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "customer_creation": {
        "default": "5/minute",
        "GET": "15/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "daily_attendance_reg": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "daily_trip_assignment": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "daily_trip_collection_point": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "daily_trip_household_collection": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "daily_trip_log": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "daily_waste_comparison": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "dashboard_summary": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "dashboard_widget_permission": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "department": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "designation": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "district": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "district_body_dashboard": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "district_leader_login": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "feed_back": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "fuel": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "government_staff_user_type": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "local_body_dashboard": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "login_audit": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "main_screen": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "main_screen_type": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "monthly_waste_comparison_report": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "municipality": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "my_trip_today": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "my_trips_today": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "panchayat_leader_login": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "panchayat_union": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "panhayat": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "permission": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "permission_assign_api": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "platform_login": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "property": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "public_grievance": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "recognize": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "refresh_token": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "register": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "scan_bin": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "staff": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "staff_access_configuration": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "staff_access_dashboard": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "staff_audit": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "staff_notification": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "staff_profile": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "staff_template": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "staff_user_type": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "staffcreation": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "state": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "state_body_dashboard": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "state_daily_waste_comparison": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "state_leader_login": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "state_monthly_waste_comparison": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "sub_property": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "town_panchayat": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "trip_attendance": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "trip_history": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "trip_lifecycle": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "trip_plan": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "trip_retrip_request": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "unassigned_staff_pool": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "user_charge_rule": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "user_permissions_api": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "user_screen": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "user_screen_action": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "user_screen_columns_api": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "user_screen_permission": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "user_type": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "validate_bin_qr": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "vehicle_breakdown": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "vehicle_creation": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "vehicle_type_creation": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "ward": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "waste_collection": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "waste_collection_bluetooth": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "waste_collection_main": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "waste_collection_sub": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
    "waste_type": {
        "default": "5/minute",
        "GET": "5/minute",
        "POST": "5/minute",
        "PUT": "5/minute",
        "PATCH": "5/minute",
        "DELETE": "5/minute",
    },
}

